DBT_1:
  outputs:
    dev:
      dataset: gcp_bq
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: abc-123
      threads: 1
      type: bigquery
  target: dev
